### ISSUE TITLE
Intelligentes Umbuchen

### ISSUE THREAD

**Issue by KevinStarWars** [tobka777/zedd2#4]
Nach deutschem Arbeitsgesetz ist es nicht erlaubt länger als zehn Stunden zu arbeiten. Eine KI, die automatisch umbucht und die Stunden auf andere Tage verteilt, wäre ein klasse Feature.
Optional, könnte nach zehn Stunden eine Notification kommen, die vor dem Übertreten von zehn Stunden warnt.

**Comment by ediekman** [comment]
> Optional, könnte nach zehn Stunden eine Notification kommen, die vor dem Übertreten von zehn Stunden warnt.

Ich würde eher dies als Feature-Request ansehen und die "intelligente Umbuchfunktion" als optional. Es wäre auch möglich bei der Übermittlung an Clarity ein Hinweis zu geben, dass die angegebenen Buchungen die max. Arbeitszeit (hier ohne Angabe von rechtlichen Gründen - kann auch durch den Arbeitgeber angeordnet sein) überschreitet und ob man es korrigieren möchte.

**Comment by NaridaL** [comment]
![image](https://user-images.githubusercontent.com/10828874/111911823-53600b80-8a67-11eb-8b73-71e583af987b.png)
